# Fundamentals of PyTorch

In [23]:
from __future__ import print_function
import torch
import numpy as np

### Initializing an Empty Tensor

In [7]:
x_empty = torch.empty(5,3)
print(x_empty)

tensor([[ 0.0000e+00, -1.0842e-19,  0.0000e+00],
        [-1.0842e-19,  3.1146e-34,  1.4013e-45],
        [-4.0679e-01,  4.5904e-41, -4.0679e-01],
        [ 4.5904e-41,  1.9780e-34,  1.4013e-45],
        [ 1.9323e-34,  1.4013e-45,  0.0000e+00]])


### Constructing a Random Tensor

In [9]:
x_random = torch.rand(5,3)
print(x_random)

tensor([[0.4249, 0.6234, 0.2851],
        [0.5703, 0.9686, 0.4853],
        [0.8137, 0.6528, 0.1516],
        [0.6215, 0.5290, 0.3865],
        [0.8489, 0.1133, 0.2333]])


### Constructing a Tensor of Zeros & Long Type

In [10]:
x_zeros = torch.zeros(5,3, dtype=torch.long)
print(x_zeros)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


### Constructing a Tensor from Custom Data

In [12]:
x_data = torch.tensor([5.5,3])
print(x_data)

tensor([5.5000, 3.0000])


## Operations


### Addition

In [13]:
x_1 = torch.rand(5,3)
y_1 = torch.rand(5,3)
print(x_1 + y_1)

tensor([[1.5141, 0.2535, 1.3723],
        [1.3621, 1.5364, 1.0101],
        [1.2397, 0.8494, 0.3390],
        [1.3062, 1.3928, 0.8883],
        [1.4581, 1.4869, 0.8269]])


In [15]:
print(torch.add(x_1,y_1))

tensor([[1.5141, 0.2535, 1.3723],
        [1.3621, 1.5364, 1.0101],
        [1.2397, 0.8494, 0.3390],
        [1.3062, 1.3928, 0.8883],
        [1.4581, 1.4869, 0.8269]])


In [16]:
result = torch.empty(5,3)
torch.add(x_1,y_1, out=result)
print(result)

tensor([[1.5141, 0.2535, 1.3723],
        [1.3621, 1.5364, 1.0101],
        [1.2397, 0.8494, 0.3390],
        [1.3062, 1.3928, 0.8883],
        [1.4581, 1.4869, 0.8269]])


In [18]:
print(y_1.add_(x_1))

tensor([[1.5141, 0.2535, 1.3723],
        [1.3621, 1.5364, 1.0101],
        [1.2397, 0.8494, 0.3390],
        [1.3062, 1.3928, 0.8883],
        [1.4581, 1.4869, 0.8269]])


### Resizing

In [20]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) #The dimension from -1 is inferred based on other provided dimension
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### Converting Torch Tensor to Numpy Array

In [24]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


### Converting Numpy Array to Torch Tensor

In [25]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
